In [19]:
import cv2
import time


img_counter = 1
#video = cv2.VideoCapture(0)

img_file_path = "./pictures_test/"

video = cv2.VideoCapture(0)

for a in range(5):
    t0 = time.time()
    frame = 0;
    
    #video = cv2.VideoCapture(0)
    
    check, frame = video.read()
    print(frame)
    #video.release()
    
    t1 = time.time()
    print(t1-t0)
    img_name = "opencv_frame_{}.png".format(img_counter)
    #cv2.imwrite(img_name, frame)
    cv2.imwrite(str(img_file_path+img_name), frame)
    img_counter += 1
    print(img_name)
    #video.release()
    time.sleep(1)
    #cv2.waitKey(100)

video.release()

None
0.00113296508789
opencv_frame_1.png
[[[  0   0   3]
  [  0   0   3]
  [  0  10   9]
  ...
  [ 11  55  79]
  [  0  54  77]
  [  0  55  78]]

 [[  0   1   0]
  [  0   1   0]
  [  0   9   5]
  ...
  [  0  33  67]
  [  0  32  66]
  [  0  32  66]]

 [[  0   1   2]
  [  0   1   2]
  [  0   1   3]
  ...
  [  0  37  72]
  [  0  39  76]
  [  0  39  76]]

 ...

 [[ 97  96  78]
  [ 91  90  72]
  [ 93  88  75]
  ...
  [217 220 224]
  [215 218 222]
  [215 218 222]]

 [[ 97 101  89]
  [ 88  93  80]
  [ 86  88  83]
  ...
  [221 220 223]
  [224 216 218]
  [224 216 218]]

 [[ 95 101  97]
  [ 79  84  81]
  [ 72  81  82]
  ...
  [219 219 219]
  [227 215 212]
  [227 215 212]]]
0.962767124176
opencv_frame_2.png
[[[  0   1   5]
  [  0   3   7]
  [  0   1   3]
  ...
  [ 25  55  80]
  [ 26  62  83]
  [ 25  61  82]]

 [[  0   2   2]
  [  0   2   2]
  [  0   1   2]
  ...
  [  4  45  66]
  [  8  50  73]
  [  3  46  68]]

 [[  0   1   3]
  [  0   1   3]
  [  0   1   2]
  ...
  [  0  37  64]
  [  0  55  80]
 

In [ ]:
import cv2
import time


img_counter = 1
#video = cv2.VideoCapture(0)

img_file_path = "./pictures_test/"

t0 = time.time()

while (time.time()-t0)<2.0:
    t1 = time.time()
    video = cv2.VideoCapture(0)
    print('video_capture: ' + str(time.time()-t1))
    
    t1 = time.time()
    check, frame = video.read()
    print('video_read: ' + str(time.time()-t1))
    
    t2 = time.time()
    img_name = "opencv_frame_{}.png".format(img_counter)
    print('img_name: ' + str(time.time()-t2))
    
    t3 = time.time()
    cv2.imwrite(str(img_file_path+img_name), frame)
    print('imwrite: ' + str(time.time()-t3))
    
    t4 = time.time()
    img_counter += 1
    print('img_counter: ' + str(time.time()-t4))
    
    t5 = time.time()
    print(img_name)
    print('print: ' + str(time.time()-t5))
    
    t6 = time.time()    
    video.release()
    print('release: ' + str(time.time()-t6))
    
print("FERTIG")

In [17]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',frame)
    
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
